### PR TITLE
Add 'khaeru' to recipe-maintainers

### PR DESCRIPTION
**Pull request by khaeru**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by khaeru** [comment]
@conda-forge-admin, please rerender

**Comment by gidden** [comment]
Looks like a SHA mismatch?

```
Downloading source to cache: v0.1.3_bf4e86a942.tar.gz
Downloading https://github.com/iiasa/ixmp/archive/v0.1.3.tar.gz
INFO:conda_build.source:Downloading source to cache: v0.1.3_bf4e86a942.tar.gz
INFO:conda_build.source:Downloading https://github.com/iiasa/ixmp/archive/v0.1.3.tar.gz
Success
INFO:conda_build.source:Success
SHA256 mismatch: 'd8e2d56079fa869629b4c92311c8719e8036bf85f8680725273f7d4214970809' != 'bf4e86a942ef27e5df190a374b2890fd3f4833354c5c45862f8ac99cbb73f336'
```
Which I don't fully understand..

**Comment by gidden** [comment]
I should clarify that I don't understand why this is failing, since at one point it passed. I don't believe we've edited anything on the github side..

I also observe the same behavior on a fresh download:

```
$ sha256sum ~/work/downloads/ixmp-0.1.3.tar.gz 
d8e2d56079fa869629b4c92311c8719e8036bf85f8680725273f7d4214970809  /home/gidden/work/downloads/ixmp-0.1.3.tar.gz
```

Both the last PR on ixmp-feedstock and the release are dated Nov 21, 2018, so nothing has changed there... a mystery..

**Comment by gidden** [comment]
Hey @khaeru, the thought here is that something on Github's backend services caused an update to the hosted tarballs (e.g., more efficient compression or something else). Can you update the hash therefore in `recipe.yml` to match `d8e2d56079fa869629b4c92311c8719e8036bf85f8680725273f7d4214970809` please?

**Comment by gidden** [comment]
lgtm, thanks!

**Pull request merged**
